model_meta:
  name: lp_proxy
  pclass: optimization
  ptype: lp
  architecture: feedforward
  activation: relu
  check: constraint
  report: 'no'
  solver: gurobi
  engine: crown
proxy_spec:
  nn_path: models/lp_example.pt
  opt_path: models/lp_physics.py
