model_meta:
  name: lp_proxy
  pclass: optimization
  ptype: lp
  architecture: feedforward
  activation: relu
  check: distance
  report: yes
  solver: gurobi
  engine: milp
proxy_spec:
  nn_path: models/lp_example.pt
  opt_path: models/lp_physics.py
